name: 'Check Package Version'
description: 'Check npm package version and whether it has been published yet'
author: 'PostHog'
inputs:
    path:
        required: false
        description: 'Path to the npm package'
        default: '.'
    fail-on-new-package:
        required: false
        description: 'Whether to fail if the package has not been published yet'
        default: 'false'
outputs:
    committed-version:
        description: 'Version now commited to the repo'
    published-version:
        description: 'Latest version published to npm, based on `dist-tags`'
    is-new-version:
        description: 'Whether repo version is yet new to npm (`"true"` or `"false"`)'
    is-new-package:
        description: 'Whether repo package has not been published yet (`"true"` or `"false"`)'
runs:
    using: 'node20'
    main: 'dist/index.js'
branding:
    icon: 'loader'
    color: 'orange'
